### ISSUE TITLE
Add z-index grouping

### ISSUE THREAD

**Issue by blairwilcox** [gitrit/pending#17]
I think it would be a good idea to add some z-index groupings to the variables file. Something like:
- $header: 5000
- $graph: 1000
- etc...

Within each section there could be layers organized in the 100s, such as
- $layer1: 100
- $layer2: 200
- $layer3: 300
- etc...

and apply them:
calc($header + $layer1)

This would ensure that elements are consistently ordered and won't class with eachother

**Comment by aaronsky** [comment]
What's the status of this?
